import {
  Globe,
  Search,
  Share2,
  Megaphone,
  Target,
  Palette,
  Brain,
  FileText,
} from "lucide-react";

/*
 * Color themes intentionally mirror the palette already assigned to each
 * service in src/components/landing/Services.jsx, so a service's identity
 * stays consistent between the homepage card and its dedicated page.
 */
const themes = {
  emerald: {
    chip: "bg-emerald-100 text-emerald-700",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-600",
    heading: "text-emerald-600",
    solid: "bg-emerald-600",
    solidHover: "hover:bg-emerald-700",
    border: "border-emerald-200",
    borderHover: "hover:border-emerald-300",
    ring: "shadow-emerald-600/20",
    soft: "bg-emerald-50",
  },
  orange: {
    chip: "bg-orange-100 text-orange-700",
    iconBg: "bg-orange-50",
    iconText: "text-orange-600",
    heading: "text-orange-600",
    solid: "bg-orange-600",
    solidHover: "hover:bg-orange-700",
    border: "border-orange-200",
    borderHover: "hover:border-orange-300",
    ring: "shadow-orange-600/20",
    soft: "bg-orange-50",
  },
  pink: {
    chip: "bg-pink-100 text-pink-700",
    iconBg: "bg-pink-50",
    iconText: "text-pink-600",
    heading: "text-pink-600",
    solid: "bg-pink-600",
    solidHover: "hover:bg-pink-700",
    border: "border-pink-200",
    borderHover: "hover:border-pink-300",
    ring: "shadow-pink-600/20",
    soft: "bg-pink-50",
  },
  blue: {
    chip: "bg-blue-100 text-blue-700",
    iconBg: "bg-blue-50",
    iconText: "text-blue-600",
    heading: "text-blue-600",
    solid: "bg-blue-600",
    solidHover: "hover:bg-blue-700",
    border: "border-blue-200",
    borderHover: "hover:border-blue-300",
    ring: "shadow-blue-600/20",
    soft: "bg-blue-50",
  },
  violet: {
    chip: "bg-violet-100 text-violet-700",
    iconBg: "bg-violet-50",
    iconText: "text-violet-600",
    heading: "text-violet-600",
    solid: "bg-violet-600",
    solidHover: "hover:bg-violet-700",
    border: "border-violet-200",
    borderHover: "hover:border-violet-300",
    ring: "shadow-violet-600/20",
    soft: "bg-violet-50",
  },
  amber: {
    chip: "bg-amber-100 text-amber-700",
    iconBg: "bg-amber-50",
    iconText: "text-amber-600",
    heading: "text-amber-600",
    solid: "bg-amber-600",
    solidHover: "hover:bg-amber-700",
    border: "border-amber-200",
    borderHover: "hover:border-amber-300",
    ring: "shadow-amber-600/20",
    soft: "bg-amber-50",
  },
  cyan: {
    chip: "bg-cyan-100 text-cyan-700",
    iconBg: "bg-cyan-50",
    iconText: "text-cyan-600",
    heading: "text-cyan-600",
    solid: "bg-cyan-600",
    solidHover: "hover:bg-cyan-700",
    border: "border-cyan-200",
    borderHover: "hover:border-cyan-300",
    ring: "shadow-cyan-600/20",
    soft: "bg-cyan-50",
  },
  red: {
    chip: "bg-red-100 text-red-700",
    iconBg: "bg-red-50",
    iconText: "text-red-500",
    heading: "text-red-500",
    solid: "bg-red-500",
    solidHover: "hover:bg-red-600",
    border: "border-red-200",
    borderHover: "hover:border-red-300",
    ring: "shadow-red-500/20",
    soft: "bg-red-50",
  },
};

export const servicesData = [
  {
    slug: "website-design-development",
    navLabel: "Website Design",
    title: "Website Design & Development",
    icon: Globe,
    theme: themes.emerald,
    eyebrow: "Website Design & Development",
    h1: "Websites built to load fast, look sharp, and convert",
    lede:
      "We design and build custom websites on a modern stack — no bloated templates, no slow themes. Every page is engineered around one goal: turning visitors into customers.",
    metaDescription:
      "Custom, responsive website design and development for Canadian businesses. Fast, conversion-focused sites built on a modern stack.",
    heroStats: [
      { value: "200+", label: "Sites shipped" },
      { value: "<2s", label: "Avg. load time" },
      { value: "100%", label: "Mobile-responsive" },
    ],
    features: [
      { title: "Custom UI/UX Design", description: "Every layout is designed from scratch around your brand and your customers — never a recycled template." },
      { title: "Modern Development", description: "Built on fast, modern frameworks with clean code that's easy to maintain and simple to scale." },
      { title: "Conversion-Focused Layout", description: "Calls-to-action, forms, and page flow are structured around what makes visitors take action." },
      { title: "CMS & Easy Editing", description: "Update text, images, and pages yourself with a simple content system — no developer required." },
      { title: "Speed & Security", description: "Optimized assets, clean hosting setup, and SSL by default so your site is fast and safe." },
      { title: "SEO-Ready Foundation", description: "Proper heading structure, metadata, and clean markup so your new site is ready to rank from day one." },
    ],
    process: [
      { title: "Discovery", description: "We learn your business, your customers, and what the site needs to accomplish." },
      { title: "Design", description: "Wireframes and visual design, reviewed with you before a single line of code is written." },
      { title: "Build", description: "Development on a modern, responsive stack with regular preview links for feedback." },
      { title: "Launch & Support", description: "We deploy, test across devices, and stay on for ongoing updates and support." },
    ],
    stats: [
      { value: "200+", label: "Websites delivered" },
      { value: "98%", label: "Client retention" },
      { value: "+220%", label: "Avg. signup lift" },
      { value: "24/7", label: "Support access" },
    ],
    faqs: [
      { question: "How long does a new website take?", answer: "Most business websites take 3–6 weeks from kickoff to launch, depending on the number of pages and how much custom functionality is involved." },
      { question: "Will I be able to update the site myself?", answer: "Yes. We build on a content management system so you can edit text, swap images, and add pages without touching code." },
      { question: "Do you build e-commerce sites?", answer: "We do — from small product catalogs to full online stores with payments, inventory, and order management." },
      { question: "What happens after launch?", answer: "We offer ongoing support plans for updates, monitoring, and small changes, so your site keeps running smoothly long after launch." },
    ],
    related: ["seo-services", "branding-graphic-design", "content-creation"],
    ctaTitle: "Ready for a website that actually converts?",
    ctaDesc: "Tell us about your business and we'll put together a free site plan and quote — no obligation.",
  },
  {
    slug: "seo-services",
    navLabel: "SEO",
    title: "SEO Services",
    icon: Search,
    theme: themes.orange,
    eyebrow: "SEO Services",
    h1: "Rank higher on Google, without the guesswork",
    lede:
      "We combine technical fixes, on-page optimization, and content strategy into one SEO roadmap built around your keywords, your competitors, and your market.",
    metaDescription:
      "Data-driven SEO services for Canadian businesses. Technical SEO, on-page optimization, link building, and local SEO to grow organic rankings.",
    heroStats: [
      { value: "150+", label: "Campaigns run" },
      { value: "4.9★", label: "Client rating" },
      { value: "7+", label: "Years in SEO" },
    ],
    features: [
      { title: "Technical SEO Audit", description: "We find and fix crawl errors, slow pages, and structural issues holding your rankings back." },
      { title: "On-Page Optimization", description: "Titles, meta descriptions, headings, and content refined around the keywords your customers actually search." },
      { title: "Keyword & Competitor Research", description: "We map the terms worth ranking for and study exactly how your competitors are winning them." },
      { title: "Link Building", description: "Earned, relevant backlinks that build authority the way search engines actually reward." },
      { title: "Local SEO", description: "Google Business Profile optimization and local citations so you show up in searches near you." },
      { title: "Reporting & Rank Tracking", description: "Monthly reports on rankings, traffic, and what's working — in plain language, not just charts." },
    ],
    process: [
      { title: "Audit", description: "Full technical and content audit to see exactly where your site stands today." },
      { title: "Strategy", description: "A keyword and content roadmap prioritized by opportunity and competition." },
      { title: "Execution", description: "On-page fixes, content, and link building rolled out on a consistent monthly cadence." },
      { title: "Measure & Refine", description: "We track rankings and traffic monthly and adjust the plan as results come in." },
    ],
    stats: [
      { value: "150+", label: "SEO campaigns" },
      { value: "Top-3", label: "Rankings achieved" },
      { value: "98%", label: "Client retention" },
      { value: "$500+", label: "Starting monthly plans" },
    ],
    faqs: [
      { question: "How much does SEO cost?", answer: "Campaigns typically start around $500/month, scaled to your industry, competition, and goals — we'll quote a plan after a quick audit." },
      { question: "How long until I see results?", answer: "Early technical fixes can help within weeks, but meaningful ranking movement usually takes 3–6 months of consistent work." },
      { question: "Do you guarantee page-one rankings?", answer: "No agency can honestly guarantee a specific rank — search algorithms change constantly. What we commit to is a transparent, consistent process and monthly reporting on real progress." },
      { question: "What's included in reporting?", answer: "Monthly reports cover keyword rankings, organic traffic, and the specific work completed that month, explained in plain terms." },
    ],
    related: ["website-design-development", "content-creation", "ai-marketing-solutions"],
    ctaTitle: "Let's find out where your SEO stands",
    ctaDesc: "Get a free SEO audit and a straightforward plan for growing your organic traffic.",
  },
  {
    slug: "social-media-marketing",
    navLabel: "Social Media",
    title: "Social Media Marketing",
    icon: Share2,
    theme: themes.pink,
    eyebrow: "Social Media Marketing",
    h1: "Social media that builds a real audience",
    lede:
      "We plan, create, and manage social content that sounds like your brand — then back it with paid campaigns and community management that keep people engaged.",
    metaDescription:
      "Social media marketing and content management for Canadian brands. Strategy, content, community management, and paid social that drives engagement.",
    heroStats: [
      { value: "+250%", label: "Avg. awareness lift" },
      { value: "120%", label: "Avg. ROAS" },
      { value: "Daily", label: "Content cadence available" },
    ],
    features: [
      { title: "Content Strategy", description: "A content calendar built around your goals, your audience, and what actually performs on each platform." },
      { title: "Content Creation", description: "Graphics, short-form video, and captions produced in-house and matched to your brand voice." },
      { title: "Community Management", description: "Comments, DMs, and reviews handled promptly, so your audience feels heard, not ignored." },
      { title: "Paid Social Campaigns", description: "Targeted ad campaigns layered on top of organic content to accelerate reach and conversions." },
      { title: "Audience Research", description: "We study who's actually engaging with your brand to sharpen targeting and messaging." },
      { title: "Performance Reporting", description: "Clear monthly reporting on engagement, growth, and what content is driving results." },
    ],
    process: [
      { title: "Brand & Audience Review", description: "We study your brand voice, past content, and audience to set a baseline." },
      { title: "Content Planning", description: "A monthly content calendar mapped to campaigns, promotions, and key dates." },
      { title: "Creation & Publishing", description: "Content is produced, approved by you, and published on a consistent schedule." },
      { title: "Engage & Optimize", description: "We manage community interaction and adjust the plan based on what's performing." },
    ],
    stats: [
      { value: "+250%", label: "Brand awareness" },
      { value: "120%", label: "Average ROAS" },
      { value: "98%", label: "Client retention" },
      { value: "24/7", label: "Community monitoring" },
    ],
    faqs: [
      { question: "Which platforms do you manage?", answer: "Most commonly Instagram, Facebook, LinkedIn, and TikTok — we recommend the mix based on where your customers actually spend time." },
      { question: "Do you create the content or do we?", answer: "We handle content creation end to end, from graphics to short-form video and captions, with your approval before anything goes live." },
      { question: "Can you run paid ads too?", answer: "Yes — organic content and paid social campaigns are managed together so they reinforce each other." },
      { question: "How is success measured?", answer: "We track engagement rate, follower growth, and, for paid campaigns, conversions and ROAS — reported monthly in plain language." },
    ],
    related: ["meta-ads", "content-creation", "branding-graphic-design"],
    ctaTitle: "Ready to build a social presence that converts?",
    ctaDesc: "Get a free content audit and see what a consistent, strategic social plan could look like for your brand.",
  },
  {
    slug: "google-ads",
    navLabel: "Google Ads",
    title: "Google Ads Management",
    icon: Megaphone,
    theme: themes.blue,
    eyebrow: "Google Ads",
    h1: "Google Ads campaigns built for ROI, not just clicks",
    lede:
      "We plan, launch, and continuously optimize Google Ads campaigns across search, shopping, display, and YouTube — with every dollar tracked back to real leads and sales.",
    metaDescription:
      "Expert Google Ads management for Canadian businesses — search, display, shopping, and YouTube campaigns optimized for conversions.",
    heroStats: [
      { value: "+340%", label: "Avg. campaign ROI" },
      { value: "100+", label: "Accounts managed" },
      { value: "Google Partner", label: "Certified status" },
    ],
    features: [
      { title: "Keyword & Market Research", description: "We identify high-intent keywords your customers are actually searching, and the ones worth avoiding." },
      { title: "Ad Copy & Creative", description: "Search ads, display banners, and shopping feeds written and designed to earn the click and the conversion." },
      { title: "Campaign Structure & Bidding", description: "Accounts structured for Quality Score and budgets managed with a bidding strategy matched to your goals." },
      { title: "Conversion Tracking Setup", description: "Proper tracking so you know exactly which campaigns and keywords produce leads or sales." },
      { title: "A/B Testing", description: "Ongoing testing of ad copy, landing pages, and audiences to keep cost-per-conversion moving down." },
      { title: "Transparent Reporting", description: "Monthly reports showing spend, conversions, and cost-per-lead — no vanity metrics." },
    ],
    process: [
      { title: "Audit & Setup", description: "We review any existing account or build a new one, with tracking configured correctly from day one." },
      { title: "Campaign Launch", description: "Campaigns go live with tightly targeted keywords, audiences, and ad creative." },
      { title: "Optimize Weekly", description: "Bids, budgets, and ad copy are adjusted weekly based on real performance data." },
      { title: "Report Monthly", description: "You get a clear monthly report on spend, results, and what's changing next." },
    ],
    stats: [
      { value: "+340%", label: "Average ROI" },
      { value: "100+", label: "Accounts managed" },
      { value: "98%", label: "Client retention" },
      { value: "Google Partner", label: "Certified agency" },
    ],
    faqs: [
      { question: "What's the minimum ad budget?", answer: "We work with a range of budgets, but generally recommend at least $1,000/month in ad spend to gather enough data to optimize effectively." },
      { question: "Do you manage Shopping and YouTube ads too?", answer: "Yes — search, shopping, display, and YouTube can all be managed under one account strategy or run individually." },
      { question: "How is my budget spent?", answer: "Ad spend goes directly to Google; our management fee is separate and covers strategy, setup, and ongoing optimization." },
      { question: "How soon will I see leads or sales?", answer: "Search campaigns can start generating traffic within days, though optimizing cost-per-conversion typically takes 4–8 weeks of data." },
    ],
    related: ["meta-ads", "seo-services", "website-design-development"],
    ctaTitle: "Want ad spend that actually pays off?",
    ctaDesc: "Get a free Google Ads account review and a straightforward plan for improving your ROI.",
  },
  {
    slug: "meta-ads",
    navLabel: "Meta Ads",
    title: "Meta Ads (Facebook & Instagram)",
    icon: Target,
    theme: themes.violet,
    eyebrow: "Meta Ads",
    h1: "Facebook & Instagram ads that find your exact customer",
    lede:
      "We build and manage Meta Ads campaigns — from audience targeting to creative to retargeting funnels — so every impression works toward a lead or a sale.",
    metaDescription:
      "Meta Ads management for Facebook and Instagram. Targeting, creative, and retargeting funnels built to convert for Canadian businesses.",
    heroStats: [
      { value: "120%", label: "Avg. ROAS" },
      { value: "+180%", label: "Avg. sales lift" },
      { value: "Meta Partner", label: "Certified status" },
    ],
    features: [
      { title: "Advanced Audience Targeting", description: "Custom and lookalike audiences built from your existing customers to find more people like them." },
      { title: "Creative Ad Design", description: "Static, carousel, and video ad creative designed to perform in-feed and in Stories." },
      { title: "Retargeting Funnels", description: "Multi-step retargeting that re-engages visitors and cart-abandoners until they convert." },
      { title: "Ad Copywriting", description: "Copy tested across angles and hooks to find what resonates before scaling budget." },
      { title: "Budget & Bid Optimization", description: "Budgets shifted toward the audiences and creative that are actually converting." },
      { title: "Performance Reporting", description: "Clear reporting on reach, cost-per-result, and ROAS every month." },
    ],
    process: [
      { title: "Audience & Creative Planning", description: "We define target audiences and build a first set of creative to test." },
      { title: "Campaign Launch", description: "Campaigns launch across Facebook and Instagram with proper pixel and conversion tracking." },
      { title: "Test & Learn", description: "We test creative angles and audiences at small budget before scaling what performs." },
      { title: "Scale & Retarget", description: "Winning campaigns get more budget, backed by a retargeting funnel for warm audiences." },
    ],
    stats: [
      { value: "120%", label: "Average ROAS" },
      { value: "+180%", label: "Sales increase" },
      { value: "98%", label: "Client retention" },
      { value: "Meta Partner", label: "Certified agency" },
    ],
    faqs: [
      { question: "Facebook or Instagram — which is better?", answer: "It depends on your audience and product. We typically run both from one campaign and let the data show where your customers respond best." },
      { question: "Do you design the ad creative?", answer: "Yes — our team designs static, carousel, and video creative in-house, tailored to your brand." },
      { question: "What is retargeting and do I need it?", answer: "Retargeting shows ads to people who've already visited your site or engaged with your content. It's usually one of the highest-ROI parts of a Meta Ads funnel." },
      { question: "How do you measure success?", answer: "Primarily cost-per-result and ROAS, tied back to your actual business goal — leads, purchases, or bookings." },
    ],
    related: ["google-ads", "social-media-marketing", "branding-graphic-design"],
    ctaTitle: "Ready for Meta Ads that pay for themselves?",
    ctaDesc: "Get a free account review and a testing plan built around your product and budget.",
  },
  {
    slug: "branding-graphic-design",
    navLabel: "Branding",
    title: "Branding & Graphic Design",
    icon: Palette,
    theme: themes.amber,
    eyebrow: "Branding & Graphic Design",
    h1: "A brand identity people actually remember",
    lede:
      "From logo to full brand guidelines, we build visual identities that set you apart and give every piece of marketing you create a consistent, recognizable look.",
    metaDescription:
      "Branding and graphic design services for Canadian businesses — logo design, brand guidelines, and marketing collateral that stand out.",
    heroStats: [
      { value: "200+", label: "Brands designed" },
      { value: "100%", label: "Custom, no templates" },
      { value: "5+", label: "Years in branding" },
    ],
    features: [
      { title: "Logo Design", description: "A distinctive, versatile logo designed to work everywhere from a favicon to a storefront sign." },
      { title: "Brand Guidelines", description: "Colors, typography, and usage rules documented so your brand stays consistent across every team and platform." },
      { title: "Marketing Collateral", description: "Business cards, brochures, presentation decks, and print materials designed to match your identity." },
      { title: "Brand Positioning", description: "We help define what your brand stands for and how it should sound before we design a single asset." },
      { title: "Packaging & Signage", description: "Product packaging and physical signage designed to carry your identity into the real world." },
      { title: "Social & Digital Assets", description: "Templates for social posts, email, and ads so your online presence looks unmistakably yours." },
    ],
    process: [
      { title: "Discovery & Positioning", description: "We learn your business, your competitors, and what your brand needs to communicate." },
      { title: "Concept Design", description: "Initial logo and visual direction concepts presented for your feedback." },
      { title: "Refinement", description: "The chosen direction is refined into a final logo and full color and type system." },
      { title: "Guidelines & Handoff", description: "A brand guideline document and asset package delivered, ready to use everywhere." },
    ],
    stats: [
      { value: "200+", label: "Brands designed" },
      { value: "98%", label: "Client retention" },
      { value: "100%", label: "Custom design" },
      { value: "5+", label: "Years experience" },
    ],
    faqs: [
      { question: "Do you offer full rebrands or just logos?", answer: "Both — we work with new businesses starting from scratch and established businesses looking to modernize an existing identity." },
      { question: "What's included in brand guidelines?", answer: "Logo usage rules, a full color palette, typography system, and examples of the brand applied across common materials." },
      { question: "How many logo concepts will I see?", answer: "Typically two to three distinct concepts at the first round, refined based on your feedback into a final design." },
      { question: "Can you design print materials too?", answer: "Yes — business cards, brochures, packaging, signage, and presentation decks are all part of our design services." },
    ],
    related: ["website-design-development", "content-creation", "social-media-marketing"],
    ctaTitle: "Ready for a brand identity that stands out?",
    ctaDesc: "Tell us about your business and get a free consultation on where your brand stands today.",
  },
  {
    slug: "ai-marketing-solutions",
    navLabel: "AI Marketing",
    title: "AI Marketing Solutions",
    icon: Brain,
    theme: themes.cyan,
    eyebrow: "AI Marketing Solutions",
    h1: "Marketing that works while you sleep",
    lede:
      "We build AI-powered chatbots, automation, and predictive analytics into your marketing so leads get answered instantly and decisions are backed by data, not guesswork.",
    metaDescription:
      "AI-powered marketing solutions — chatbots, predictive analytics, and automation to help Canadian businesses market smarter.",
    heroStats: [
      { value: "24/7", label: "Automated lead response" },
      { value: "+30%", label: "Avg. lead capture lift" },
      { value: "5+", label: "Years applying AI" },
    ],
    features: [
      { title: "AI Chatbots", description: "Trained on your business to answer common questions and qualify leads instantly, day or night." },
      { title: "Predictive Analytics", description: "Data models that flag which leads are most likely to convert, so your team focuses effort where it counts." },
      { title: "Marketing Automation", description: "Email sequences, follow-ups, and lead nurturing that run automatically based on customer behavior." },
      { title: "AI-Assisted Content", description: "AI-drafted content, refined by our team, to speed up production without losing your brand voice." },
      { title: "Personalization Engines", description: "Website and email content that adapts to each visitor based on behavior and past interactions." },
      { title: "Performance Dashboards", description: "Live dashboards pulling your key marketing metrics into one place, updated automatically." },
    ],
    process: [
      { title: "Opportunity Audit", description: "We map where leads are lost, where response is slow, and where data isn't being used." },
      { title: "Solution Design", description: "We choose the right tools — chatbot, automation, or analytics — for the specific gap." },
      { title: "Build & Integrate", description: "Solutions are built and connected to your existing site, CRM, or ad platforms." },
      { title: "Monitor & Improve", description: "We track performance and refine the automation as more data comes in." },
    ],
    stats: [
      { value: "24/7", label: "Lead response" },
      { value: "+30%", label: "Lead capture lift" },
      { value: "98%", label: "Client retention" },
      { value: "5+", label: "Years in AI marketing" },
    ],
    faqs: [
      { question: "Is this just a generic chatbot plugin?", answer: "No — chatbots are trained on your specific business, services, and FAQs, not a generic script." },
      { question: "Will AI replace my marketing team?", answer: "No. These tools handle repetitive tasks and surface data so your team can focus on strategy and relationships, not replace judgment." },
      { question: "What tools do you integrate with?", answer: "Most common CRMs, email platforms, and website builders — we'll confirm compatibility with your existing stack during the audit." },
      { question: "Is my customer data secure?", answer: "Yes — data handling follows standard security practices, and we'll walk through specifics for your setup before anything goes live." },
    ],
    related: ["seo-services", "google-ads", "website-design-development"],
    ctaTitle: "Curious what AI could automate in your marketing?",
    ctaDesc: "Get a free opportunity audit and see where automation could save time and capture more leads.",
  },
  {
    slug: "content-creation",
    navLabel: "Content",
    title: "Content Creation",
    icon: FileText,
    theme: themes.red,
    eyebrow: "Content Creation",
    h1: "Content that educates, engages, and converts",
    lede:
      "From blog posts to video scripts, we create content that sounds like your brand, speaks to your customers, and gives your SEO and social channels something worth sharing.",
    metaDescription:
      "Content creation services for Canadian brands — blog posts, website copy, video scripts, and social content that engages and converts.",
    heroStats: [
      { value: "500+", label: "Pieces produced" },
      { value: "98%", label: "Client retention" },
      { value: "All formats", label: "Written, visual, video" },
    ],
    features: [
      { title: "Blog & Article Writing", description: "SEO-informed articles that answer real customer questions and support your organic rankings." },
      { title: "Website Copywriting", description: "Homepage, service page, and landing page copy written to explain your value clearly and drive action." },
      { title: "Video Scripts", description: "Scripts for social, ads, and explainer videos structured to hook attention and hold it." },
      { title: "Email Campaigns", description: "Newsletter and campaign copy that keeps subscribers engaged without feeling like spam." },
      { title: "Social Media Content", description: "Captions and posts tailored to each platform's tone, from LinkedIn to Instagram." },
      { title: "Content Strategy", description: "A content calendar and topic plan built around your goals, not just a random posting schedule." },
    ],
    process: [
      { title: "Brand & Voice Review", description: "We study your brand, past content, and audience to define a consistent voice." },
      { title: "Content Planning", description: "A topic and channel plan built around your goals and calendar." },
      { title: "Drafting & Review", description: "Content is drafted and shared for your feedback before anything is finalized." },
      { title: "Publish & Repurpose", description: "Final content is published and repurposed across additional channels where it fits." },
    ],
    stats: [
      { value: "500+", label: "Pieces produced" },
      { value: "98%", label: "Client retention" },
      { value: "All formats", label: "Written & video" },
      { value: "On-brand", label: "Every single time" },
    ],
    faqs: [
      { question: "What types of content do you produce?", answer: "Blog articles, website copy, email campaigns, social captions, and scripts for video and ads — whatever channels your strategy calls for." },
      { question: "Will content sound like my brand?", answer: "Yes — we start with a voice and brand review so every piece reads consistently, whether it's a blog post or a tweet." },
      { question: "Do you handle SEO for blog content?", answer: "Blog content is written with keyword research and on-page SEO best practices built in from the first draft." },
      { question: "How much content will I receive each month?", answer: "Volume is scoped to your plan and channels — we'll confirm cadence and deliverables before starting." },
    ],
    related: ["seo-services", "social-media-marketing", "branding-graphic-design"],
    ctaTitle: "Need content that actually sounds like you?",
    ctaDesc: "Get a free content review and a sample plan for your blog, site, or social channels.",
  },
];

export function getServiceBySlug(slug) {
  return servicesData.find((s) => s.slug === slug);
}
