import { Code, Megaphone, Stethoscope, Search, Layers, ShoppingCart } from "lucide-react";

const themes = {
  emerald: {
    chip: "bg-emerald-100 text-emerald-700",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-600",
    heading: "text-emerald-600",
    solid: "bg-emerald-600",
    solidHover: "hover:bg-emerald-700",
    border: "border-emerald-200",
    borderHover: "hover:border-emerald-300",
    ring: "shadow-emerald-600/20",
    soft: "bg-emerald-50",
  },
  orange: {
    chip: "bg-orange-100 text-orange-700",
    iconBg: "bg-orange-50",
    iconText: "text-orange-600",
    heading: "text-orange-600",
    solid: "bg-orange-600",
    solidHover: "hover:bg-orange-700",
    border: "border-orange-200",
    borderHover: "hover:border-orange-300",
    ring: "shadow-orange-600/20",
    soft: "bg-orange-50",
  },
  blue: {
    chip: "bg-blue-100 text-blue-700",
    iconBg: "bg-blue-50",
    iconText: "text-blue-600",
    heading: "text-blue-600",
    solid: "bg-blue-600",
    solidHover: "hover:bg-blue-700",
    border: "border-blue-200",
    borderHover: "hover:border-blue-300",
    ring: "shadow-blue-600/20",
    soft: "bg-blue-50",
  },
  pink: {
    chip: "bg-pink-100 text-pink-700",
    iconBg: "bg-pink-50",
    iconText: "text-pink-600",
    heading: "text-pink-600",
    solid: "bg-pink-600",
    solidHover: "hover:bg-pink-700",
    border: "border-pink-200",
    borderHover: "hover:border-pink-300",
    ring: "shadow-pink-600/20",
    soft: "bg-pink-50",
  },
  violet: {
    chip: "bg-violet-100 text-violet-700",
    iconBg: "bg-violet-50",
    iconText: "text-violet-600",
    heading: "text-violet-600",
    solid: "bg-violet-600",
    solidHover: "hover:bg-violet-700",
    border: "border-violet-200",
    borderHover: "hover:border-violet-300",
    ring: "shadow-violet-600/20",
    soft: "bg-violet-50",
  },
  amber: {
    chip: "bg-amber-100 text-amber-700",
    iconBg: "bg-amber-50",
    iconText: "text-amber-600",
    heading: "text-amber-600",
    solid: "bg-amber-600",
    solidHover: "hover:bg-amber-700",
    border: "border-amber-200",
    borderHover: "hover:border-amber-300",
    ring: "shadow-amber-600/20",
    soft: "bg-amber-50",
  },
};

export const portfolio = [
  { 
    title: "FreshBite E-Commerce Redesign", 
    slug: "freshbite-ecommerce",
    navLabel: "FreshBite",
    category: "Website Design & SEO", 
    description: "Complete e-commerce overhaul resulting in 180% increase in online sales.", 
    tags: ["Shopify", "SEO", "UI/UX"], 
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80", 
    stat: "+180% Sales", 
    bg: "bg-emerald-100", 
    borderHover: "hover:border-emerald-200",
    color: "text-emerald-600",
    icon: ShoppingCart,
    theme: themes.emerald,
    eyebrow: "Case Study: FreshBite",
    h1: "Transforming an E-Commerce Experience for a 180% Sales Boost",
    lede: "We completely redesigned FreshBite's Shopify storefront, focusing on mobile responsiveness, checkout flow optimization, and aggressive SEO strategies.",
    metaDescription: "Case study: How we helped FreshBite increase online sales by 180% through a complete Shopify redesign and SEO overhaul.",
    heroStats: [
      { value: "+180%", label: "Online Sales" },
      { value: "45%", label: "Organic Traffic" },
      { value: "6 Months", label: "Timeframe" },
    ],
    features: [
      { title: "Custom Shopify Theme", description: "Built a highly responsive and lightning-fast custom Shopify theme tailored to the brand's aesthetic." },
      { title: "Frictionless Checkout", description: "Redesigned the checkout process to reduce cart abandonment by 25%." },
      { title: "Technical SEO Audit", description: "Resolved hundreds of crawl errors and optimized site architecture for better indexing." },
      { title: "Product Page Optimization", description: "Enhanced product descriptions and imagery, adding structured data for rich snippets." },
      { title: "Mobile-First Design", description: "Ensured a seamless shopping experience on all mobile devices, where 70% of traffic originated." },
      { title: "Conversion Rate Optimization", description: "Implemented strategic A/B testing on call-to-actions and trust signals." },
    ],
    process: [
      { title: "Discovery & Strategy", description: "Analyzed existing analytics to identify drop-off points and high-value keywords." },
      { title: "UI/UX Design", description: "Created wireframes and high-fidelity mockups focusing on user journey and brand consistency." },
      { title: "Development & Migration", description: "Developed the custom Shopify theme and safely migrated all products and SEO value." },
      { title: "Launch & Monitoring", description: "Launched the new site and closely monitored performance metrics to ensure immediate growth." },
    ],
    stats: [
      { value: "+180%", label: "Online Sales" },
      { value: "45%", label: "Organic Traffic Growth" },
      { value: "-25%", label: "Cart Abandonment" },
      { value: "<1.5s", label: "Page Load Time" },
    ],
    faqs: [
      { question: "What platform was used?", answer: "We utilized Shopify Advanced for its robust e-commerce capabilities and scalability." },
      { question: "How long did the redesign take?", answer: "The entire process, from discovery to launch, took approximately 8 weeks." },
      { question: "Did you handle the SEO migration?", answer: "Yes, we meticulously mapped all 301 redirects to ensure no organic traffic was lost during the transition." },
      { question: "What was the biggest challenge?", answer: "Optimizing the high-resolution product imagery without sacrificing page load speed was critical." },
    ],
    related: ["urbannest-real-estate", "techflow-saas"],
    ctaTitle: "Ready to scale your e-commerce store?",
    ctaDesc: "Let's discuss how a strategic redesign and SEO overhaul can multiply your revenue.",
  },
  { 
    title: "UrbanNest Real Estate", 
    slug: "urbannest-real-estate",
    navLabel: "UrbanNest",
    category: "Web Development & Branding", 
    description: "Modern property listing platform generating 3x more qualified leads.", 
    tags: ["Next.js", "AI", "Branding"], 
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80", 
    stat: "3x Leads", 
    bg: "bg-orange-50", 
    borderHover: "hover:border-orange-200",
    color: "text-orange-600",
    icon: Search,
    theme: themes.orange,
    eyebrow: "Case Study: UrbanNest",
    h1: "Revolutionizing Property Search with Next.js & AI",
    lede: "We built a cutting-edge real estate platform for UrbanNest, featuring AI-powered property recommendations and a blazing-fast user interface.",
    metaDescription: "Case study: See how UrbanNest achieved 3x more qualified leads with a custom Next.js property listing platform and AI features.",
    heroStats: [
      { value: "3x", label: "Qualified Leads" },
      { value: "-40%", label: "Bounce Rate" },
      { value: "Next.js", label: "Tech Stack" },
    ],
    features: [
      { title: "Next.js Architecture", description: "Utilized Next.js for server-side rendering, ensuring ultra-fast page loads and superior SEO." },
      { title: "AI Property Match", description: "Integrated an AI recommendation engine to suggest properties based on user browsing behavior." },
      { title: "Interactive Map Search", description: "Built a highly responsive map interface for intuitive neighborhood exploration." },
      { title: "Brand Identity Refresh", description: "Modernized UrbanNest's logo, color palette, and typography for a premium feel." },
      { title: "Agent Dashboard", description: "Developed a custom backend portal for agents to seamlessly manage listings and leads." },
      { title: "Automated CRM Sync", description: "Connected lead capture forms directly to their Salesforce CRM for instant follow-up." },
    ],
    process: [
      { title: "Requirement Gathering", description: "Conducted deep-dive workshops with top agents to understand their workflow and pain points." },
      { title: "Prototyping", description: "Created interactive prototypes to validate the new property search experience." },
      { title: "Full-Stack Build", description: "Developed the frontend with Next.js/React and built a robust Node.js API layer." },
      { title: "Deployment", description: "Deployed on Vercel for edge network performance and seamless continuous integration." },
    ],
    stats: [
      { value: "3x", label: "Qualified Leads" },
      { value: "50k+", label: "Monthly Visitors" },
      { value: "-40%", label: "Bounce Rate" },
      { value: "100%", label: "Agent Adoption" },
    ],
    faqs: [
      { question: "Why choose Next.js?", answer: "Next.js provided the perfect balance of SEO capabilities (via SSR) and a highly interactive React frontend." },
      { question: "How does the AI feature work?", answer: "It analyzes user search parameters and click history to surface similar properties they might have missed." },
      { question: "Is the platform scalable?", answer: "Absolutely. The headless architecture allows it to handle millions of listings without performance degradation." },
    ],
    related: ["freshbite-ecommerce", "healthfirst-clinic"],
    ctaTitle: "Want to dominate your local real estate market?",
    ctaDesc: "Contact us to build a digital platform that attracts buyers and empowers your agents.",
  },
  { 
    title: "HealthFirst Clinic", 
    slug: "healthfirst-clinic",
    navLabel: "HealthFirst",
    category: "Google Ads & SEO", 
    description: "Digital marketing strategy achieving top-3 Google rankings.", 
    tags: ["Google Ads", "Local SEO", "Content"], 
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=600&q=80", 
    stat: "Top-3 Ranking", 
    bg: "bg-blue-50", 
    borderHover: "hover:border-blue-200",
    color: "text-blue-600",
    icon: Stethoscope,
    theme: themes.blue,
    eyebrow: "Case Study: HealthFirst",
    h1: "Dominating Local Healthcare Search Results",
    lede: "We executed a hyper-targeted Local SEO and Google Ads campaign to establish HealthFirst Clinic as the premier choice in their city.",
    metaDescription: "Case study: How HealthFirst Clinic achieved Top-3 Google rankings and a surge in new patient bookings through our SEO and Ads strategy.",
    heroStats: [
      { value: "Top-3", label: "Google Rankings" },
      { value: "+210%", label: "New Patient Calls" },
      { value: "-15%", label: "Cost Per Lead" },
    ],
    features: [
      { title: "Google Business Profile Optimization", description: "Completely overhauled their GBP with targeted keywords, updated services, and consistent posting." },
      { title: "Hyper-Local Google Ads", description: "Ran geofenced search campaigns targeting high-intent keywords like 'urgent care near me'." },
      { title: "Medical Content Strategy", description: "Produced authoritative, medically accurate blog content to establish E-E-A-T." },
      { title: "Review Generation Campaign", description: "Implemented an automated system to request reviews from satisfied patients." },
      { title: "Landing Page Optimization", description: "Created dedicated landing pages for specific treatments to increase ad conversion rates." },
      { title: "Call Tracking Setup", description: "Utilized dynamic number insertion to accurately attribute phone calls to specific marketing channels." },
    ],
    process: [
      { title: "Local Market Analysis", description: "Analyzed competitor visibility and identified gaps in local search volume." },
      { title: "Foundation Setup", description: "Claimed and optimized all major local directories and healthcare citations." },
      { title: "Campaign Execution", description: "Launched Google Ads concurrently with the long-term SEO strategy." },
      { title: "Ongoing Optimization", description: "Continuously refined ad copy and negative keyword lists to minimize wasted spend." },
    ],
    stats: [
      { value: "Top-3", label: "For 15+ Keywords" },
      { value: "+210%", label: "New Patient Calls" },
      { value: "4.8★", label: "Google Rating Achieved" },
      { value: "-15%", label: "Cost Per Lead" },
    ],
    faqs: [
      { question: "How long did it take to rank?", answer: "Local map pack rankings improved within 2 months, while organic rankings solidified around month 5." },
      { question: "Were the Google Ads expensive?", answer: "Healthcare CPCs can be high, but by focusing on high-intent, long-tail keywords, we kept the CPA highly profitable." },
      { question: "Did you manage HIPAA compliance?", answer: "Yes, all tracking and lead generation mechanisms were configured to maintain strict patient privacy standards." },
    ],
    related: ["stylehub-fashion", "greenleaf-cannabis"],
    ctaTitle: "Need more patients for your clinic?",
    ctaDesc: "Let's diagnose your current digital presence and prescribe a growth strategy.",
  },
  { 
    title: "StyleHub Fashion", 
    slug: "stylehub-fashion",
    navLabel: "StyleHub",
    category: "Social Media & Meta Ads", 
    description: "Full-funnel campaign driving 250% increase in brand awareness.", 
    tags: ["Meta Ads", "Content", "Strategy"], 
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80", 
    stat: "120% ROAS", 
    bg: "bg-pink-50", 
    borderHover: "hover:border-pink-200",
    color: "text-pink-600",
    icon: Megaphone,
    theme: themes.pink,
    eyebrow: "Case Study: StyleHub",
    h1: "Scaling an Indie Fashion Brand with Meta Ads",
    lede: "We designed a full-funnel social media strategy and aggressive Meta Ads campaign to catapult StyleHub from a niche boutique to a recognized national brand.",
    metaDescription: "Case study: See how we achieved a 120% ROAS and 250% brand awareness increase for StyleHub using advanced Meta Ads.",
    heroStats: [
      { value: "120%", label: "Average ROAS" },
      { value: "+250%", label: "Brand Awareness" },
      { value: "3.5x", label: "Social Following" },
    ],
    features: [
      { title: "Dynamic Product Ads (DPA)", description: "Implemented retargeting campaigns showcasing the exact products users previously viewed." },
      { title: "Influencer Whitelisting", description: "Ran ads through the accounts of micro-influencers to boost authenticity and click-through rates." },
      { title: "Viral Reels Strategy", description: "Produced high-energy, trend-focused short-form video content for organic reach." },
      { title: "Lookalike Audience Expansion", description: "Leveraged past purchaser data to find highly qualified new prospects across North America." },
      { title: "Creative A/B Testing", description: "Continuously tested lifestyle imagery vs. product-focused shots to optimize cost per purchase." },
      { title: "UGC Campaign", description: "Encouraged User Generated Content through incentives, providing a steady stream of authentic ad material." },
    ],
    process: [
      { title: "Creative Production", description: "Organized a multi-day photoshoot to build a massive library of high-quality ad assets." },
      { title: "Funnel Construction", description: "Built distinct campaigns for Top of Funnel (Awareness), Middle (Consideration), and Bottom (Conversion)." },
      { title: "Testing Phase", description: "Ran low-budget tests across 20+ audience and creative combinations to find winners." },
      { title: "Scaling", description: "Aggressively scaled budget vertically into the top-performing ad sets while maintaining ROAS." },
    ],
    stats: [
      { value: "120%", label: "Return on Ad Spend" },
      { value: "15k+", label: "New Customers" },
      { value: "+250%", label: "Brand Search Volume" },
      { value: "-30%", label: "Customer Acquisition Cost" },
    ],
    faqs: [
      { question: "What was the primary ad format?", answer: "Video ads (Reels and Stories formats) significantly outperformed static images for cold audiences." },
      { question: "How did iOS 14+ affect the campaign?", answer: "We implemented the Meta Conversions API (CAPI) early, minimizing data loss and maintaining accurate tracking." },
      { question: "How often was creative refreshed?", answer: "We introduced new ad creatives every two weeks to prevent ad fatigue." },
    ],
    related: ["greenleaf-cannabis", "freshbite-ecommerce"],
    ctaTitle: "Ready to make your brand go viral?",
    ctaDesc: "Partner with us to create thumb-stopping content and high-converting ad campaigns.",
  },
  { 
    title: "TechFlow SaaS", 
    slug: "techflow-saas",
    navLabel: "TechFlow",
    category: "Website Design & Content", 
    description: "High-converting landing page improving trial signups by 220%.", 
    tags: ["React", "Copywriting", "CRO"], 
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80", 
    stat: "+220% Signups", 
    bg: "bg-violet-50", 
    borderHover: "hover:border-violet-200",
    color: "text-violet-600",
    icon: Code,
    theme: themes.violet,
    eyebrow: "Case Study: TechFlow",
    h1: "Engineering a B2B Landing Page that Converts",
    lede: "We transformed TechFlow's complex software offering into a compelling, easy-to-understand narrative that drove a massive 220% increase in free trial signups.",
    metaDescription: "Case study: Discover how our conversion-focused design and persuasive copywriting increased TechFlow's SaaS trial signups by 220%.",
    heroStats: [
      { value: "+220%", label: "Trial Signups" },
      { value: "4.2%", label: "Conversion Rate" },
      { value: "React", label: "Frontend Framework" },
    ],
    features: [
      { title: "Persuasive Copywriting", description: "Distilled complex technical features into clear, benefit-driven messaging targeting decision-makers." },
      { title: "Interactive Product Demos", description: "Built lightweight, interactive UI components allowing users to 'test drive' features before signing up." },
      { title: "Social Proof Integration", description: "Strategically placed customer testimonials, logos, and case study snippets to build instant trust." },
      { title: "Frictionless Signup Flow", description: "Redesigned the onboarding form, reducing required fields and implementing single sign-on (SSO)." },
      { title: "Performance Engineering", description: "Optimized React bundle sizes to ensure near-instant load times, crucial for B2B ad traffic." },
      { title: "Heatmap Analytics", description: "Installed Hotjar to track user scrolling and clicking behavior, informing continuous tweaks." },
    ],
    process: [
      { title: "Message Mapping", description: "Interviewed current users to understand their 'Aha!' moments and pain points." },
      { title: "Wireframing & Copy", description: "Developed the page narrative and structure simultaneously to ensure perfect alignment." },
      { title: "Development", description: "Built the custom landing page using React and Framer Motion for subtle, premium animations." },
      { title: "A/B Testing", description: "Ran continuous split tests on headlines and CTA button colors to maximize the conversion rate." },
    ],
    stats: [
      { value: "+220%", label: "Free Trial Signups" },
      { value: "4.2%", label: "Overall Conversion Rate" },
      { value: "-45%", label: "Cost Per Acquisition" },
      { value: "+60%", label: "Time on Page" },
    ],
    faqs: [
      { question: "Why React for a landing page?", answer: "React allowed us to build the complex, interactive product demo components seamlessly." },
      { question: "What was the winning A/B test?", answer: "Changing the CTA from 'Start Free Trial' to 'See How It Works' increased clicks by 35%." },
      { question: "Did you write the copy?", answer: "Yes, our specialized B2B copywriters handled all messaging and narrative structure." },
    ],
    related: ["urbannest-real-estate", "healthfirst-clinic"],
    ctaTitle: "Is your SaaS product struggling to convert traffic?",
    ctaDesc: "Let's redesign your funnel to clearly communicate your value and capture more leads.",
  },
  { 
    title: "GreenLeaf Cannabis", 
    slug: "greenleaf-cannabis",
    navLabel: "GreenLeaf",
    category: "Full Digital Marketing", 
    description: "End-to-end digital presence driving 400% revenue growth.", 
    tags: ["Branding", "Ads", "SEO"], 
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80", 
    stat: "+400% Revenue", 
    bg: "bg-amber-50", 
    borderHover: "hover:border-amber-200",
    color: "text-amber-600",
    icon: Layers,
    theme: themes.amber,
    eyebrow: "Case Study: GreenLeaf",
    h1: "Navigating Strict Regulations for 400% Retail Growth",
    lede: "We built a compliant, highly effective digital ecosystem for GreenLeaf Cannabis, dominating local SEO and leveraging programmatic advertising to drive unprecedented foot traffic.",
    metaDescription: "Case study: Learn how our full-service digital strategy helped GreenLeaf Cannabis achieve 400% revenue growth despite strict industry regulations.",
    heroStats: [
      { value: "+400%", label: "Revenue Growth" },
      { value: "#1", label: "Local Search Rank" },
      { value: "3", label: "New Locations Opened" },
    ],
    features: [
      { title: "Compliant SEO Strategy", description: "Navigated complex advertising restrictions by focusing heavily on un-restricted organic search growth." },
      { title: "Programmatic Display Ads", description: "Utilized age-gated programmatic networks to serve compliant ads to highly targeted local audiences." },
      { title: "Menu Integration", description: "Seamlessly integrated their Dutchie inventory system into a custom-designed, fast-loading website." },
      { title: "Brand Identity Creation", description: "Developed a modern, approachable brand identity that stood out in a saturated, cliché market." },
      { title: "Email Marketing (Age-Gated)", description: "Built a robust, compliant email list for direct communication of promotions and new drops." },
      { title: "Local Citation Building", description: "Ensured perfect NAP (Name, Address, Phone) consistency across hundreds of directories." },
    ],
    process: [
      { title: "Regulatory Review", description: "Worked closely with legal counsel to ensure all marketing strategies strictly adhered to national and provincial laws." },
      { title: "Platform Build", description: "Designed and developed the e-commerce/click-and-collect website." },
      { title: "Omnichannel Launch", description: "Rolled out the new brand identity simultaneously across digital, print, and in-store signage." },
      { title: "Ongoing Dominance", description: "Continuously published educational content to build authority and capture top-of-funnel search traffic." },
    ],
    stats: [
      { value: "+400%", label: "Year-Over-Year Revenue" },
      { value: "#1", label: "Ranking for 'Dispensary Near Me'" },
      { value: "12k+", label: "Email Subscribers Built" },
      { value: "3", label: "New Retail Locations" },
    ],
    faqs: [
      { question: "How did you advertise without Google/Meta Ads?", answer: "We focused on robust Local SEO and utilized specific programmatic display networks that allow age-gated cannabis advertising." },
      { question: "Was the website an e-commerce store?", answer: "It functioned as a 'click-and-collect' model, integrating directly with their point-of-sale inventory." },
      { question: "What was the key to the brand's success?", answer: "Moving away from traditional 'stoner' tropes to a modern, retail-forward aesthetic that appealed to a broader demographic." },
    ],
    related: ["stylehub-fashion", "freshbite-ecommerce"],
    ctaTitle: "Operating in a highly regulated industry?",
    ctaDesc: "We know how to navigate the rules while still delivering explosive growth. Let's talk.",
  },
];

export function getPortfolioBySlug(slug) {
  return portfolio.find((p) => p.slug === slug);
}
